### ISSUE TITLE
Problem spinning up Graphite using Synthesize and Vagrant on Windows 8

### ISSUE THREAD

**Issue by helsing** [obfuscurity/synthesize#21]
I am trying to spin up Graphite using Synthesize and Vagrant on my Windows 8 machine. The provisioning step fails with an ": invalid option" error. Any suggestions?

$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'synthesize'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: synthesize_default_1415917860626
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 443 => 8443 (adapter 1)
    default: 8125 => 8125 (adapter 1)
    default: 2003 => 22003 (adapter 1)
    default: 2004 => 22004 (adapter 1)
    default: 22 => 2222 (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
==> default: Machine booted and ready!
GuestAdditions 4.3.10 running --- OK.
==> default: Checking for guest additions in VM...
==> default: Mounting shared folders...
    default: /vagrant => C:/Users/Workspace/synthesize
==> default: Running provisioner: shell...
    default: Running: inline script
stdin: is not a tty
: invalid option
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

chmod +x /tmp/vagrant-shell && /tmp/vagrant-shell

Stdout from the command:

Stderr from the command:

stdin: is not a tty
: invalid option
$

**Comment by iamamuc** [comment]
I ran into this issue as well.  dos2unix does fix this if you have already deployed and want to manually install.

Setting the Git value for core.autocrlf to "input" made sure the unix style line feeds were kept and I was able to deploy without having to run dos2unix and manually install.

**Comment by obfuscurity** [comment]
There is no obvious change to the affected file after running dos2unix on it, so there's nothing I can fix natively. Added a warning to the README, hopefully this helps future users. Closing this out.

**Comment by cgatian** [comment]
My quick fix was to open the file using Notepad++ and switching from DOS/Windows to UNIX by double clicking the text in the status bar.

![image](https://cloud.githubusercontent.com/assets/1752170/8463509/c0310c34-2008-11e5-96e6-3ea59cc77271.png)

**Comment by Ajedi32** [comment]
@obfuscurity You might want to try adding something like this to the repository's `.gitattributes` file:

```
* text=auto eol=lf
```

That will ensure that git doesn't change the files in Windows checkouts to use Windows-style line endings.

See https://help.github.com/articles/dealing-with-line-endings/

**Comment by obfuscurity** [comment]
Thanks for the suggestion @Ajedi32, added.
