### ISSUE TITLE
Conflict when reading Linux release version

### ISSUE THREAD

**Issue by inkel** [obfuscurity/synthesize#26]
Hi @obfuscurity. First of all: thank you for this repo and great work on _Monitoring with Graphite_, I'm loving it so far.

I've tried to install `synthesize` by cloning and running `vagrant up` on my OSX 10.9.5. Provisioning failed with a `Sorry, this is only supported for Ubuntu Linux 14.04`, but the VM was up, so I did a `vagrant ssh` and executed the following:

```
vagrant@vagrant-ubuntu-trusty-64:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty
```

Checking the corresponding line in the `install` script, I've found:

```
UBUNTU_RELEASE=`lsb_release -a 2>/dev/null | grep '^Descrip' | cut -s -f 2`

# …

if [[ ! $UBUNTU_RELEASE =~ 'Ubuntu 14.04.1 LTS' ]]; then
  echo "Sorry, this is only supported for Ubuntu Linux 14.04."
  exit 1
fi
```

I've updated the script to check against `14.04.2` instead and now works. Would you like me to send a pull request?

**Comment by obfuscurity** [comment]
That would be great, and thanks for the kind words. Should be fine to just change that string from `Ubuntu 14.04.1 LTS` to `Ubuntu 14.04`.

**Comment by obfuscurity** [comment]
P.S. There are some other fixes I need to merge but it hadn't occurred to me (lol) that people would actually be using this project **while** I'm writing the book. I'll get on those soonish.
