### ISSUE TITLE
Support for cacert file

### ISSUE THREAD

**Issue by praste** [obfuscurity/synthesize#30]
Installation was failings as `pip` could not download required software due to cacert. Looks like pip does support `--cert` option. 
Can we add optional parameter to specify path to local CA bundles

**Comment by obfuscurity** [comment]
Can you elaborate on this?

**Comment by praste** [comment]
When I tried to run on a machine (behind a proxy)at my company, `pip install` command failed due to certificate validation.

`pip` does support option to provide path to certificate file. If script can add an option to provide path to certificate file, it would be great. I believe syntax looks like 

`pip install --cert <path_to_cert_file>`

**Comment by obfuscurity** [comment]
Curious which other options to pip might be useful. I don't mind adding support to help folks traverse proxies but it'd be nice to knock them all out at once. Some candidates:

* `--proxy`
* `--retries`
* `--timeout`
* `--cert`
* `--client-cert`

**Comment by praste** [comment]
I was able get it working using `--cert`

**Comment by obfuscurity** [comment]
Apologies for letting this issue go untouched for so long. I doubt this is still a valid issue but if it is, please try the latest release and report back.

https://github.com/obfuscurity/synthesize/releases/tag/v4.0.0
