### ISSUE TITLE
Invalid admin username and password in documentation

### ISSUE THREAD

**Issue by marrrvin** [obfuscurity/synthesize#32]
Valid name is default now.

**Comment by cmdel** [comment]
I'm trying to login to the Graphite Account/Login, but the credentials you give for Django don't seem to work. I then try to change the password for the admin user, and get an erro: "Error: user 'admin' does not exists."
Any thoughts as to what I'm doing wrong here?

Thanks

**Comment by obfuscurity** [comment]
Pretty sure this is related to #28. I'm going to address this issue this weekend (finally!). :pray:

**Comment by obfuscurity** [comment]
This is fixed now. The credentials in the documentation are correct, it was an issue with the Django fixture.

**Comment by cmdel** [comment]
So admin, graphite_me_synthesize, are now the correct credentials?
Is there a way to fix an already existing installation?

**Comment by obfuscurity** [comment]
Those were always the intended credentials. If your superuser failed to be created you can run these commands to add one.

```
$ cd /opt/graphite/webapp/graphite
$ sudo python manage.py createsuperuser
```

If you'd prefer to destroy your existing database and recreate it with the fixed version (this won't affect metrics, but will destroy any graphs or dashboards you've saved since the installation):

```
$ sudo su -
# cd /opt/graphite/webapp/graphite
# curl https://raw.githubusercontent.com/obfuscurity/synthesize/master/templates/graphite/webapp/initial_data.json > initial_data.json
# rm /opt/graphite/storage/graphite.db
# python manage.py syncdb --noinput
```
