### ISSUE TITLE
Document how to "reset" data to clean slate

### ISSUE THREAD

**Issue by armon** [obfuscurity/synthesize#35]
It would be awesome to have a script or just docs detailing how we can reset to a clean slate. I mean to wipe out all data in whisper / graphite, and start from scratch without rebuilding the VM.

**Comment by obfuscurity** [comment]
Uh, huhuh. https://github.com/obfuscurity/synthesize#removal

**Comment by armon** [comment]
@obfuscurity I don't mean to remove the installation of all the packages and configuration, just to clear the existing data. I'm trying to just optimize the time of iteration for testing streaming data, clearing data, and then streaming in a new set.

**Comment by armon** [comment]
I think it might be as simple as nuking the whisper directory, but not sure

**Comment by obfuscurity** [comment]
Oh, well yeah, that's easy.

```
$ sudo rm -rf /opt/graphite/storage/whisper/*
```

**Comment by armon** [comment]
Thanks!
