### ISSUE TITLE
Disabling Graphite HTTPS

### ISSUE THREAD

**Issue by cgatian** [obfuscurity/synthesize#37]
Sorry not very familiar with Unix. Is there a way to disable HTTPS on the Graphite server? 

I think I am running into issues hooking up the HTTPS data source from graphite to a non HTTPs Grafana server.

**Comment by obfuscurity** [comment]
It's easy enough to enable a non-HTTPS port, it's just Apache.

**Comment by cgatian** [comment]
During the installation do I change the port in graphite.conf?

![image](https://cloud.githubusercontent.com/assets/1752170/8554580/872b4c06-24b8-11e5-874f-d2b05f586416.png)

**Comment by cgatian** [comment]
Sorry, totally clueless on what to do.  I've tried modifying the graphite.conf file to specify a virtual port.  I saved the file and then ran *sudo service apache2 restart*, and while that did say it successfully restarted, it didn't do anything.  I verified virtual box is properly forwarding the port.

![image](https://cloud.githubusercontent.com/assets/1752170/8557928/ab7aa370-24ce-11e5-8855-cf8d2f5a43c9.png)

Could you please provide some guidance on how to remove SSL?

Thank you

**Comment by cgatian** [comment]
Sorry just ran across porst.conf ... I think I have it now

**Comment by obfuscurity** [comment]
Sorry, it was a busy day. Was planning to get back to look at this during the evening but it appears that you've got it running? If you're still running into issues please let me know.

**Comment by cgatian** [comment]
I figured it out :+1: Thank you for taking the time to respond.
