### ISSUE TITLE
Services not starting

### ISSUE THREAD

**Issue by mmarkzon** [obfuscurity/synthesize#44]
carbon-cache and statsite are not starting for me.  I'm running a Vagrant VM on a Windows 2012R2 box.

For carbon-cache I get this when attempting to start similar to the install script:
vagrant@vagrant:/etc/init.d$ sudo service carbon-cache start
env: /etc/init.d/carbon-cache: No such file or directory
vagrant@vagrant:/etc/init.d$ ls -l carbon-cache
-rwxr-xr-x 1 root root 1848 Mar 29 19:47 carbon-cache

If I start carbon-cache via "sudo /opt/graphite/bin/carbon-cache.py start" it will start ok.

For statsite I get an error that it can't read the configuration file.
Mar 30 13:07:26 vagrant statsite[16986]: Failed to read the configuration file!
Mar 30 13:07:26 vagrant kernel: [58520.409881] init: statsite main process (16984) terminated with status 1

The config looks ok to me and I can start it successfully via "sudo /usr/local/sbin/statsite -f /etc/statsite.conf".

Any thoughts on how to fix or a workaround?  I would like these to start automatically when my VM reboots.  Thanks!

**Comment by mmarkzon** [comment]
I figured this out.  There were some other files that had Windows line endings that needed to be converted to dos.  I'm not sure which one's specifically fixed this because I converted them all.

**Comment by obfuscurity** [comment]
Yes, see https://github.com/obfuscurity/synthesize#installation.
