### ISSUE TITLE
Unable to find any metrics in Graphite

### ISSUE THREAD

**Issue by Orxcle-xx** [obfuscurity/synthesize#47]
Hi,

First of all, I want to thank you for your Graphite installation.
However, I am not able to import any metrics in Graphite ( I just don't see them in web interface ).
Do I need to make any other additional configuration after installing Graphite using Synthesize on DigitalOcean?

P.S
I try to send metrics using metrics.sh file ( ie by executing ./metrics.sh ) with the following content ( ip-address is valid of course ):
PORT=2003
SERVER=<ip-address>
echo "call.error 1 2016-08-19 15:46:19" | nc -c ${SERVER} ${PORT}
echo "call.error 1 2016-08-19 15:46:20" | nc -c ${SERVER} ${PORT}

Any help would be highly appreciated! Thank you in advance.

Best Regards,
Maksim

**Comment by obfuscurity** [comment]
Hi @Orxcle-xx, thanks for trying out Synthesize. It looks like your timestamp is invalid. Check out some of the examples from the official [Graphite documentation](http://graphite.readthedocs.io/en/latest/feeding-carbon.html#the-plaintext-protocol):

```
PORT=2003
SERVER=graphite.your.org
echo "local.random.diceroll 4 `date +%s`" | nc -q0 ${SERVER} ${PORT}
```

**Comment by aww-yiss** [comment]
The time stamp is incorrectly formatted, it needs to be in the form of UNIX epoch stamp. 

Try:
echo "call.error 1 `date -s`" | nc -c ${SERVER} ${PORT}

**Comment by obfuscurity** [comment]
Timely as always, @aww-yiss. 😉
