### ISSUE TITLE
unable to install on ubuntu 14.04.5

### ISSUE THREAD

**Issue by torra** [obfuscurity/synthesize#51]
Here is a snippet of code that I use to bootstrap a graphite box:
```
wget https://github.com/obfuscurity/synthesize/archive/v2.4.1.tar.gz
tar -xf v2.4.1.tar.gz
cd synthesize-2.4.1
./install
```

this fails while trying to install statsite with the following error:
``config.status: error: cannot find input file: `Makefile.in'``

I've also tried 3.0.0RC1, and it fails with the same error.

**Comment by obfuscurity** [comment]
@torra Sorry, there was another Statsite build fix in HEAD that was never formally released. Please try again with the new [v2.4.2 release](https://github.com/obfuscurity/synthesize/releases/tag/v2.4.2).

**Comment by torra** [comment]
thanks for the quick response! trying now...

**Comment by torra** [comment]
thanks @obfuscurity, it worked. i see your point about keeping the `git clone` for the sake of upgradeability. i would say checking out a specific tag is a good idea, because it would prevent silly build changes in statsite master branch from breaking synthesize install

**Comment by obfuscurity** [comment]
Cool, thanks for the bug report. 👍
