### ISSUE TITLE
total noob question: Where does this script install the tools to?? [WIN64]

### ISSUE THREAD

**Issue by seanvree** [obfuscurity/synthesize#53]
So I got the script successful on my Windows10E box.  

I'm able to bring up vagrant:

c:\synthesize>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'mayflower/trusty64-puppet3' is up to date...
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.

c:\synthesize>vagrant box list
mayflower/trusty64-puppet3 (virtualbox, 0.7.2)

So......how do I actually access the graphite and Collctd databases?  Nowhere in the readme file does it say what port this script sets the tools to???

I'm obviously missing something that I'm going to be very embarrassed about. 

thx! DOPE script!

**Comment by obfuscurity** [comment]
Hi @seanvree, thanks for the kind words. It sounds like you might be unfamiliar with Vagrant. The services are running *inside* of the virtual machine. You will access them like any other Graphite installation, via the Graphite-Web UI (or API, if you're using something like [Grafana](http://grafana.org/)).

The ports that each service is exposed on are [listed here](https://github.com/obfuscurity/synthesize#vagrant) but they assume a certain level of experience with Graphite. If you're new to Graphite, you probably won't know what each of those represent. Here's a quick breakdown:

* 8443 (Graphite-Web http UI)
* 8125 (statsd listener)
* 22003 (Carbon plaintext listener)
* 22004 (Carbon pickle listener)

Starting out, you will probably only need to work with ports 8443 and 22003 for composing graphs and submitting metrics, respectively. I would encourage you to go read about getting metrics [into](http://graphiteapp.org/quick-start-guides/feeding-metrics.html) and [out of](http://graphiteapp.org/quick-start-guides/graphing-metrics.html) the system.

Hope this helps!

**Comment by seanvree** [comment]
@obfuscurity  - Thanks! That's exactly what I was looking for. 

Now, one other question - I should be able to access those ports on the "host" machine by simply going to localhost:8443 as long as the VM  (vagrant) is UP, correct?  Or can I only access those ports within the vagrant VM?

**Comment by obfuscurity** [comment]
Yes, the ports I listed above are the ones exposed to the local (Windows) host. They're mapped by Vagrant to the actual service ports running inside the VM. The actual mapping is detailed in the README (and linked to in my earlier comment).

**Comment by seanvree** [comment]
Great! Thanks @obfuscurity !

**Comment by seanvree** [comment]
Hey @obfuscurity ,

Really appricate the helkp. Have spent many hours on this and I'm making progress.

I'm really having a hard time finding resources for Windows.  Obviously, all this stuff is meant for UNIX distributions, but I've got pretty far on this and I'm not quitting!!  Do you by chance have any resources for windows, specifically for compiling metrics? 

I've got vagrant running
I've got Graphite running
I've got Influx running
I've got Grafana running

I'm just having a problem getting the Metrics INTO graphite.  Yes, I'm a noob to this, but I understand the concepts.  I can access the graphite UI, I just can't seem to really find any resources of how to get the metrics into graphite when the main platform is windows. 

Anyway, sorry for all the noobness, I've just got so close so I thought you might be willing to steer me in the right direction. I just feel like I'm missing something simple?

Also, I downloaded your dashboard on Graphana! Great work!

**Comment by obfuscurity** [comment]
In my first reply I linked you to the [Getting Metrics into Graphite](http://graphiteapp.org/quick-start-guides/feeding-metrics.html) document. This should get you going. There really is no difference with a Synthesize-hosted Graphite, aside from the port mapping.

P.S. FWIW InfluxDB is a "competing" time-series database. I'm not sure if its relevant to this discussion, but I just figured I'd mention it since you did too. :wink:

**Comment by seanvree** [comment]
HA! I got that. Honestly, like I said, this stuff isn't designed for windows, so right now I'm trying to just see what works. 

Thanks so much sir.

**Comment by obfuscurity** [comment]
No worries. Did that answer your question or were you asking something more general like "how do you gather metrics on Windows", because that's a whole other discussion. :smile:

**Comment by seanvree** [comment]
Ha, no, you did sir. Thanks!

**Comment by seanvree** [comment]
Hey @obfuscurity !! Making progress. 

Can you give me a resource about the Collectd agent?  Didn't see any port mappings anywhere?

how do I access it?

Thanks,

**Comment by obfuscurity** [comment]
If you want to make changes to collectd, just login to the VM with `vagrant ssh`. You'll find the [configuration file](https://github.com/obfuscurity/synthesize/blob/master/templates/collectd/collectd.conf) at `/etc/collectd/collectd.conf`. Aside from the opinionated config we provide, the rest of the package is standard Ubuntu fare (e.g. restart the service with `service collectd restart`).

**Comment by seanvree** [comment]
@obfuscurity  - am I bother you with these rookie questions?  Please let me know and I'll stop. 

Okay, everything looks good in the config of collectd. 

A couple follow ups (if I may)

1 - I got access to the graphite browser, still working thru getting the metrics to populate 

possible problem -  when I'm on the Graphite UI, I see LOGIN at the top, I try to login but I'm not sure what the default creds are? I'm assuming I'm already logged in since I can see the dashboard?

2 - in grafana, I can't seem to connect to the Graphite data source 
using: 

Name: DS_Graphite
Type: Graphite

URL (This is what I'm confused on) although I've tried all the following:
http/https 
22004
22003
8125 

Auth: none

"Unknown error"

Thanks brother

-SV

**Comment by obfuscurity** [comment]
The default admin creds for **Graphite-Web** (i.e. port 8443) are [documented in the README](https://github.com/obfuscurity/synthesize#administration). The default admin creds for **Grafana** are `admin/admin`.

If you're using the Grafana included [in this pre-release](https://github.com/obfuscurity/synthesize/releases/tag/v3.0.0RC2), then it should already be configured with a working datasource for the local Graphite. I've tested it just now and it works fine for me.

If you're using a different/external Grafana, it will need to use port 8443 (Graphite-Web). You can see the datasource parameters we use [here](https://github.com/obfuscurity/synthesize/blob/v3.0.0RC2/install#L93-L95). We also install a Carbon dashboard that can be viewed [here](http://127.0.0.1:3030/dashboard/db/graphite-carbon-metrics) (assuming you're running the VM on the same host you're reading this).
