### ISSUE TITLE
AttributeError: 'module' object has no attribute 'OP_NO_TLSv1_1'

### ISSUE THREAD

**Issue by Exocomp** [obfuscurity/synthesize#59]
I'm getting this error on a stock ubuntu 14.04 LTS
```
Starting carbon-cache-1: Traceback (most recent call last):
  File "/opt/graphite/bin/carbon-cache.py", line 32, in <module>
    run_twistd_plugin(__file__)
  File "/opt/graphite/lib/carbon/util.py", line 61, in run_twistd_plugin
    from twisted.internet import epollreactor
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/epollreactor.py", line 24, in <module>
    from twisted.internet import posixbase
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 18, in <module>
    from twisted.internet import error, udp, tcp
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 28, in <module>
    from twisted.internet._newtls import (
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/_newtls.py", line 21, in <module>
    from twisted.protocols.tls import TLSMemoryBIOFactory, TLSMemoryBIOProtocol
  File "/usr/local/lib/python2.7/dist-packages/twisted/protocols/tls.py", line 63, in <module>
    from twisted.internet._sslverify import _setAcceptableProtocols
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/_sslverify.py", line 38, in <module>
    TLSVersion.TLSv1_1: SSL.OP_NO_TLSv1_1,
AttributeError: 'module' object has no attribute 'OP_NO_TLSv1_1'
failed
carbon-cache-1 not running
```

**Comment by obfuscurity** [comment]
Unless I'm mistaken, you've opened this issue, posted it to the [Graphite Answers](https://answers.launchpad.net/graphite/+question/482402) page, and emailed me at my personal address. Any one of those is fine, all three is a bit overboard. You first reached out to me this morning via email. Please understand that supporting Graphite is not my full-time job (or afaik anyone else working in the project either) and that it's a community effort to support it in our spare time. I want to help you with this issue but it means dropping other things I'm working on to pick things up and try to reproduce this problem. Your patience is appreciated.

**Comment by Exocomp** [comment]
umm, your mistaken on the email part to your personal address, that wasn't me.  I wouldn't lie to you if I did.  Looks like you owe me an apology for that.  :)

I created an issue here to let the developer know, sounds like it accomplished the task.

I created a post to the [Graphite Answers](https://answers.launchpad.net/graphite/+question/482402) because I saw that was created for the graphite community or else it wouldn't exist.

I don't think I've done anything wrong by doing those two things.

**Comment by obfuscurity** [comment]
Apologies, I guess it was a crazy coincidence. I'm glad you created the issue and there's definitely nothing wrong with posting to the Answers site for community assistance.

**Comment by obfuscurity** [comment]
@Exocomp Which release are you running?

**Comment by Exocomp** [comment]
@obfuscurity 

I'm using the quick start guide on the Graphite home page:

https://graphiteapp.org/quick-start-guides/synthesize.html

$ wget https://github.com/obfuscurity/synthesize/archive/master.zip
$ unzip master.zip
$ cd synthesize-master/
$ sudo ./install

**Comment by Exocomp** [comment]
@obfuscurity 

I stopped using synthesize and got a working solution using an alternative method.  So for me this is no longer relevant, so up to you on how you want to handle it.

**Comment by obfuscurity** [comment]
@Exocomp No worries, I appreciate you bringing it to my attention either way. I'll continue to track the issue/fix here.

**Comment by obfuscurity** [comment]
I'm not able to reproduce with the supported Vagrant configuration using [this 14.04 image](https://atlas.hashicorp.com/mayflower/boxes/trusty64-puppet3). I'll try again with a clean image and running the script manually.

```
==> default: + service carbon-cache start
==> default: Starting carbon-cache-1:
==> default: succeeded
==> default: carbon-cache-1 (pid: 17990):
==> default: running
==> default: + service memcached start
==> default: Starting memcached:
==> default: memcached.
==> default: + service collectd start
==> default:  * Starting statistics collection and monitoring daemon collectd
==> default:    ...done.
==> default: + service apache2 start
==> default:  * Starting web server apache2
==> default:  *
==> default: + service statsite start
==> default: statsite start/running, process 18163
```

**Comment by obfuscurity** [comment]
I would not be surprised to see if it was related to [this](https://github.com/graphite-project/graphite-web/issues/1721#issuecomment-253279181). Workaround suggested there.

**Comment by obfuscurity** [comment]
Same result with a fresh image and running `install` by hand.

**Comment by Exocomp** [comment]
@obfuscurity 

The steps to reproduce are:

1) Get a copy of the Ubunut Server 14.04 LTS, don't use Vagrant or anything else, just get a stock Ubuntu from their server @ http://old-releases.ubuntu.com/releases/14.04.0/ubuntu-14.04-server-amd64.iso

2) Install it on Hyper-V or VirtualBox or Vmware

3) Execute these commands

sudo wget https://github.com/obfuscurity/synthesize/archive/master.zip
sudo unzip master.zip
sudo cd synthesize-master/
sudo sudo ./install

**Comment by obfuscurity** [comment]
Confirmed the problem as described in the linked issue above. You need to uninstall python-openssl before attempting to install Graphite/Synthesize.

```
Starting carbon-cache-1: Traceback (most recent call last):
  File "/opt/graphite/bin/carbon-cache.py", line 32, in <module>
    run_twistd_plugin(__file__)
  File "/opt/graphite/lib/carbon/util.py", line 61, in run_twistd_plugin
    from twisted.internet import epollreactor
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/epollreactor.py", line 24, in <module>
    from twisted.internet import posixbase
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 18, in <module>
    from twisted.internet import error, udp, tcp
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 28, in <module>
    from twisted.internet._newtls import (
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/_newtls.py", line 21, in <module>
    from twisted.protocols.tls import TLSMemoryBIOFactory, TLSMemoryBIOProtocol
  File "/usr/local/lib/python2.7/dist-packages/twisted/protocols/tls.py", line 63, in <module>
    from twisted.internet._sslverify import _setAcceptableProtocols
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/_sslverify.py", line 38, in <module>
    TLSVersion.TLSv1_1: SSL.OP_NO_TLSv1_1,
AttributeError: 'module' object has no attribute 'OP_NO_TLSv1_1'
failed
carbon-cache-1 not running
```

**Comment by Exocomp** [comment]
@obfuscurity so by confirmed you mean you could reproduce it?  

To handle it properly, you should put that step in your install process to detect the problem and prompt the user appropriately and not just blindly error out.  Or put that step in your documentation on your site.

**Comment by obfuscurity** [comment]
@Exocomp Fair enough, I have a branch for that incoming.
