### ISSUE TITLE
Add NGINX server support

### ISSUE THREAD

**Issue by d3QUone** [obfuscurity/synthesize#61]
I guess there are a lot of developers that prefer Nginx instead of Apache
The main problem is that both Nginx and Apache binds to 80-th and 443-d port, and can not work together. And I can't install `synthesize` and quickly test the Graphite on existing "nginx-machines"

**Comment by obfuscurity** [comment]
@d3QUone I empathize, but Synthesize is an _opinionated_ installer using a very specific set of technologies. As I don't personally use Graphite with NGINX, I don't have the expertise to support that configuration effectively. IMHO, the [official Graphite documentation](http://graphite.readthedocs.io/en/latest/index.html) should include a dedicated document for NGINX installations. I'd recommend opening an issue over there for this.
