### ISSUE TITLE
Trouble with statsite on fresh install

### ISSUE THREAD

**Issue by blathering** [obfuscurity/synthesize#63]
I've just done a fresh install on Ubuntu 14.04 using synthesize and my metrics aren't appearing in graphite. I think it might be something to do with statsite but I'm having having difficulty figuring out what.

(Using netcat) metrics I send to port 2003 appear as expected and metrics from collectd are appearing.
(Using tcpdump) I can see incoming metrics on port 8125.
My application works when pointing to another graphite instance but not the fresh install.
All configuration is default.

Any help would be greatly appreciated.

**Comment by blathering** [comment]
I've just reinstalled on another fresh aws instance. *.wsp are now appearing on disk but looking at the json return from graphite-web using format=json it looks like all values are null.

This is at odds with the inbound traffic I can see which looks like: tcpdump metric.name:45|ms

**Comment by obfuscurity** [comment]
Apologies for letting this issue go untouched for so long. I doubt this is still a valid issue but if it is, please try the latest release and report back.

https://github.com/obfuscurity/synthesize/releases/tag/v4.0.0
