### ISSUE TITLE
A way to get statsite working (under systemd, on Raspbian Jessie)

### ISSUE THREAD

**Issue by Geoff99** [obfuscurity/synthesize#65]
# Getting statsite running (as a service, under systemd, on Raspbian Jessie)

Hi,

I realise this is (probably) out of scope of the project, but in case it is helpful, 
to someone I thought I would share my experiences anyway.

## Thanks!

First, a very big thanks for this. A few months back version 0.9.5 of
this project saved my sanity after I had descended into a pit of
confusion trying to get graphite working, and became completely lost
due to my almost complete ignorance about setting up and configuring
apache, Django, mod_wsgi etc.  Since I wanted to get graphite running on
a Raspberry Pi, I wasn't able to use Vagrant, but the install script
(with only a very few tweaks) got me up and running.  More on that
later.

PS The book "Monitoring with Graphite" was tremendously helpful as well.
I bought an ecopy pre-release, and read it cover to cover.

## Statsite
 I did have some trouble getting statsite working. I think I've solved
 it now, and the purpose of this post is to share what I did in case it
 might help someone else.

 When I first installed graphite I didn't need statsite (statsd) for my
 main project I so when it didn't start up properly I just put the issue to one side.  
I have only just returned to it today, having read up on many things Linux which
 I didn't even know I didn't know before :-) (such as SystemV, Upstart,
 and systemd)

 Anyway, I think there is a small bug in the install script related to
 statsite.

 The line in the install script which says

 ```
 cp ${SYNTHESIZE_HOME}/templates/init/* /etc/init/
 ```

copies a file called `templates/init/statsite.conf` to
`etc/init/statsite.conf`.  And `/etc/init/` (I learnt) is the directory
where Upstart init files live.

But later on, at the bottom of the install file there is a line which
says

```
service statsite start
```

I believe that is the **SystemV** command to start a service.  Anyway, it
didn't work for me.  From my reading the **Upstart** command should be

```
initctl statsite start
```

Unfortunately that didn't work for me either, because I am using an RPi
with Raspbian Jessie, and that version of Linux has replaced Upstart
with systemd.

But with only a bit of effort, I managed to get a systemd unit (service)
file to start and run the statsite service for me.

I called the file `example.statsite.service` and its contents are:

```
[Unit]
Description=statsite StatsD service
Wants=carbon-cache.service
After=carbon-cache.service

[Service]
#User=statsd
Type=simple
ExecStart=/usr/local/sbin/statsite -f /etc/statsite.conf
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

The following commands (I typed them interactively from the synthesize
directory where I had put `example.statsite.service`, but they could be
included in a script) successfully

* put the service file in the right location,
* enabled it, and
* started the statsite service for me

```
# Put the service file where systemd expects to find it
sudo cp example.statsite.service /etc/systemd/system/statsite.service
# Enable the service
sudo systemctl enable statsite
# Start the statsite service
sudo systemctl start statsite
# Check it started OK
sudo systemctl status statsite
# Have a look at the journal entries
sudo journalctl -u statsite
```

I've tried rebooting my Raspberry Pi, and statsite does restart as part
of the boot process :-) .

## Tweaks to `install` to make it work on a RPi

I realise the purpose of this project is deliberately limited to
Ubuntu 14.04, but just in case anyone else wants to try and use it to
get graphite working on  RPi, under Raspbian Jessie, here are the 2 tweaks
I made to the install script.  Usual caveats, all care, no
responsibility!

### Patch 1

There is a segment near the top of the install script which says:

```
if [[ ! $UBUNTU_RELEASE =~ 'Ubuntu 14.04' ]]; then
  echo "Sorry, this is only supported for Ubuntu Linux 14.04."
  exit 1
fi
```

I patched that to

```
if [[ ! $UBUNTU_RELEASE =~ 'Ubuntu 14.04' ]]; then
  echo "Sorry, this is only supported for Ubuntu Linux 14.04."
  echo "But just maybe it will work on Raspbian Jessie anyway"
  # exit 1
fi
```

### Patch 2

There is a segment towards the bottom of the install script which said:

```
# Add carbon system user and set permissions
groupadd -g 998 carbon
useradd -c "carbon user" -g 998 -u 998 -s /bin/false carbon
```

This failed for me because usergroup 998 was already spoken for on my RPi,
 as I discovered using the following command :

```
getent group | grep 998
```

But a bit of trial and error (just trying different numbers!) showed me 
that 996 was free.  I double checked with

```
getent passwd | grep 996
``` 

to confirm that user 996 was available as well, and then simply patched 
the install script as follows :

```
groupadd -g 996 carbon
useradd -c "carbon user" -g 996 -u 996 -s /bin/false carbon
```

And then, with many very sincere thanks offered to the author, 
all I needed to do from the appropriate directory was :

```
sudo ./install
```

and lo and behold, graphite was up and running for me under Raspbian 
Jessie.

### Grafana

All this was before Grafana was added to the install script.  Now I've 
shared my experience thus far, looking at whether that will work for me 
on the RPi is next on my list.

**Comment by obfuscurity** [comment]
Thanks for the writeup. I have no plans to specifically target RPi but we have a new release for Ubuntu 18.04 and Graphite 1.1.x if you'd like to check out the updates.

https://github.com/obfuscurity/synthesize/releases/tag/v4.0.0
