### ISSUE TITLE
vagrant up giving errors

### ISSUE THREAD

**Issue by saifromeo** [obfuscurity/synthesize#69]
ubuntu@ip-XXXXXX:~/synthesize-master$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The box 'mayflower/trusty64-puppet4' could not be found.

**Comment by obfuscurity** [comment]
It looks like you made an edit to the Vagrantfile. The actual version is `mayflower/trusty64-puppet3` which you can see in https://github.com/obfuscurity/synthesize/blob/master/Vagrantfile#L8.

**Comment by saifromeo** [comment]
I resynced, still see the same error 

Bringing machine 'default' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The box 'mayflower/trusty64-puppet3' could not be found.

**Comment by obfuscurity** [comment]
Seems to be working fine here. Yes, it will fail to find the box locally the first time (it should) but it should then attempt to retrieve it from the upstream mirrors (it does).

```
$ vagrant.exe up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'mayflower/trusty64-puppet3' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'mayflower/trusty64-puppet3'
    default: URL: https://vagrantcloud.com/mayflower/trusty64-puppet3
==> default: Adding box 'mayflower/trusty64-puppet3' (v0.7.2) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/mayflower/boxes/trusty64-puppet3/versions/0.7.2/providers/virtualbox.box
    default: Progress: 0% (Rate: 196k/s, Estimated time remaining: 0:44:39)
...
```
