### ISSUE TITLE
manage.py no longer present to change user password

### ISSUE THREAD

**Issue by KieranP** [obfuscurity/synthesize#70]
Docs need to be updated. manage.py no longer exists.

What is the new way to set the users password?

**Comment by obfuscurity** [comment]
Sorry, Django keeps moving the finish line. It used to be `manage.py`, then it changed to `django-admin.py`, and now it looks like they've changed it again to just `django-admin`. Long story short, your command will differ according to the version of Django installed with your graphite-web. 

I'll need to boot up a Synthesize to verify but your command will probably look like this:

```
PYTHONPATH=$GRAPHITE_ROOT/webapp django-admin changepassword admin --settings=graphite.settings
```

**Comment by obfuscurity** [comment]
Apologies for letting this issue go untouched for so long. I doubt this is still a valid issue but if it is, please try the latest release and report back.

https://github.com/obfuscurity/synthesize/releases/tag/v4.0.0
