### ISSUE TITLE
Make Grafana default on 443, Graphite from /graphite path

### ISSUE THREAD

**Issue by KieranP** [obfuscurity/synthesize#71]
I would argue that Grafana is more powerful and usable than Graphite web, and therefore should be the default when hitting port 80/443. Grafana is also served on port 3000 and doesn't support https (http://url_to_server:3000). So I would propose changed to the apache config that result in the following:

https://url_to_server                  <- Grafana
https://url_to_server/graphite   <- Graphite-web

Thoughts?

**Comment by obfuscurity** [comment]
The goal of Synthesize is to serve as an educational tool for using Graphite. It's not intended to be a production deployment strategy. We've included Grafana as a courtesy to users because it *is* a powerful tool to use *with* Graphite, but have no plans to make it the default UI.
