### ISSUE TITLE
Problem when using Synthesize in AWS instance

### ISSUE THREAD

**Issue by aalmangour** [obfuscurity/synthesize#72]
Dear All,

I'm facing a problem on a fresh AWS instance, I've noticed two issues:
1- When restarting the instance, the Grafana server doesn't startup automatically, I've to do it manually.
2- The disk gets full in 4-5 hours then the Grafana can not be used anymore. I don't know why this is happening.

**Comment by obfuscurity** [comment]
Apologies for letting this issue go untouched for so long. I doubt this is still a valid issue but if it is, please try the latest release and report back.

https://github.com/obfuscurity/synthesize/releases/tag/v4.0.0
