### ISSUE TITLE
Synthesize not working since WhiteNoise 4.0 release

### ISSUE THREAD

**Issue by IliyaNovikov** [obfuscurity/synthesize#73]
After installing Synthesize and testing Graphite-Web with "https://127.0.0.1:8443/" as suggested I got "500 Internal Server Error". In /opt/graphite/storage/log/apache2/error.log I found: "Your WhiteNoise configuration is incompatible with WhiteNoise v4.0". So followed http://whitenoise.evans.io/en/stable/changelog.html#v4-0 where it is saying that modifications are required in order to work with WhiteNoise 4.0. As my intention was only to evaluate Graphite (have no previous experience with it) I decided to work around the issue:
```
sudo pip uninstall whitenoise
sudo pip install 'whitenoise==3.3.1'
sudo reboot
```
which fixed the problem.
Much appreciate Synthesize for how it simplifies the whole Graphite setup and hope that this issue will be fixed in some proper way.

**Comment by obfuscurity** [comment]
Apologies for letting this issue go untouched for so long. I doubt this is still a valid issue but if it is, please try the latest release and report back.

https://github.com/obfuscurity/synthesize/releases/tag/v4.0.0
