### ISSUE TITLE
Installation fails (using vagrant) 

### ISSUE THREAD

**Issue by oymo** [obfuscurity/synthesize#75]
"vagrant up" fails, seemingly while attempting to set up cairocffi:

    default: Downloading/unpacking cairocffi (from -r requirements.txt (line 48))
    default:   Running setup.py (path:/tmp/pip_build_root/cairocffi/setup.py) egg_info for package cairocffi
    default:     Traceback (most recent call last):
    default:       File "<string>", line 17, in <module>
    default:       File "/tmp/pip_build_root/cairocffi/setup.py", line 7, in <module>
    default:         'cairocffi does not support Python 2.x anymore. '
    default:     RuntimeError: cairocffi does not support Python 2.x anymore. Please use Python 3 or install an older version of cairocffi.
    default:     Complete output from command python setup.py egg_info:
    default:     Traceback (most recent call last):
    default: 
    default:   File "<string>", line 17, in <module>
    default: 
    default:   File "/tmp/pip_build_root/cairocffi/setup.py", line 7, in <module>
    default: 
    default:     'cairocffi does not support Python 2.x anymore. '
    default: 
    default: RuntimeError: cairocffi does not support Python 2.x anymore. Please use Python 3 or install an older version of cairocffi.
    default: 
    default: ----------------------------------------
    default: Cleaning up...
    default: Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/cairocffi
    default: Storing debug log for failure in /root/.pip/pip.log

> The SSH command responded with a non-zero exit status. Vagrant
> assumes that this means the command failed. The output for this command
> should be in the log above. Please read the output to determine what
> went wrong.

**Comment by carlwain74** [comment]
I'm getting the same error when I try to run the installation on a clean Ubuntu 14.04 server.

Should I start a new issue or can we use the same open issue?

**Comment by obfuscurity** [comment]
No need to open duplicate issues. I'll try to look at the issue this weekend or as time permits.

**Comment by obfuscurity** [comment]
Sorry for the long delay. Synthesize needs to be updated to work with [at least] Ubuntu Xenial (16.04) and possibly Python 3.x. Trusty is EOL.

**Comment by obfuscurity** [comment]
This has been resolved in the latest release.

https://github.com/obfuscurity/synthesize/releases/tag/v4.0.0
