### ISSUE TITLE
Synthesize - switch to go-graphite stack?

### ISSUE THREAD

**Issue by obfuscurity** [obfuscurity/synthesize#78]
Hopefully some folks see this and have opinions, I'd like to hear them.

I still care deeply about the Graphite project, but after spending the better portion of a weekend trying to update Synthesize, it feels like it might be a good time to switch the underlying stack. Although I've made decent progress patching it to support the Python 3.x support in Graphite HEAD, there are still some issues in graphite-web (e.g. deprecating events) that concern me. And at least one that I'm not seeing reported yet at all... `django-admin.py migrate` appears to be broken (for python3, at least).

I run the golang equivalent of Graphite at work and it performs wonderfully. I couldn't be happier with the ease of deployment or the performance of each component: go-carbon, carbonapi, and whisper (with the Grafana UI). I would very much like others to experience the same joy that I still get out of Graphite, but that begs the question... what is Synthesize's mission?

This project's initial mission was to prove the haters wrong... that installing [the canonical Python] Graphite didn't have to be hard. And I think it succeeded for a while. I'm not convinced this is still true (especially since this project is very much broken now, and probably has been for a while). I think this is easily remedied by switching software components, but does that represent a failure of sorts? Would anyone care?

cc @deniszh @dancech

**Comment by deniszh** [comment]
I'm running python3 powered graphite-web in https://github.com/graphite-project/docker-graphite-statsd, it works quite well, especially on Django 2.x
IMO Graphite is fully Python 3 ready. Also events should run fine too, @piotr1212 fixed that up to latest Django (if we really want to deprecate it then we'll need to provide migration tool for e.g. Grafana events). 
Obviously, I was not able to test all migration variations, of course. Could you please open issue with migration problem, @obfuscurity ? I'll try to look.
About installation problem - 1) it definitely exists 2) IMO docker solved it quite good
So, Synthesize fate is up to you IMO. I'm not against switching to go-carbon or even completely to go-graphite. I still have proposition for Graphite-web version 1.2 with migration to go-carbon, but didn't finalize it yet.

**Comment by deniszh** [comment]
Here, made quick PR to Python 3 support - https://github.com/obfuscurity/synthesize/pull/79
Just for reference, I'm not mean you should use it. :)
Feel free to e.g merge it `python3`  branch and keep only for reference, and migrate to golang stack, partially or fully.

**Comment by Geoff99** [comment]
Not a comment per se on the issue of whether or not to change to the `go-graphite` stack, just a reiteration of my gratitude for how much help this project gave me in the past (see #65 ).  Many thanks once again for providing it!  Since I now have my graphite (and `statsite` and `Grafana`) installed and running smoothly, I don't *need* to use `Synthesize` regularly anymore.

PS If you were to change to the `go-graphite` stack, it would give me an opportunity to learn something new, which is always fun, next time I'm playing in this space - but that's hardly a reason for making the change :-)

PPS I use `Grafana` as my day to day UI in the setup I use "in production" (well in my hobby level production) on a Raspberry Pi, because it provides "nicer" graphing facilities.

**Comment by piotr1212** [comment]
> django-admin.py migrate appears to be broken (for python3, at least).

I'm not aware of this. Could you please provide more details, or better open an issue so I can look into it?

> there are still some issues in graphite-web (e.g. deprecating events) that concern me.

Events work (for now). I was wondering if anyone uses it/cares about it at all and if it would make sense to invest time into it in the future. I didn't get any response to that issue. Does go-carbon do events?

**Comment by deniszh** [comment]
I polished my PR, now everything works perfectly, as before.
I didn't find any issues with migrations, though.

Another possible solution - Synthesize still mentioning in Graphite documentation, if you decide to switch to go stack we can fork it into Graphite organization, e.g. as `synthesize-python`

**Comment by obfuscurity** [comment]
TBQH it's entirely possible that the migrations errors I've been hitting is a consequence of my environment (Ubuntu 16.04 Windows Linux Subsystem running Vagrant + Virtualbox).

I really appreciate all your work on this @deniszh. I think for the sake of continuity, we should keep Synthesize focused on the canonical Graphite project. If and when I choose to build one for Go-Graphite, I'll probably go with `synthesize-go`.

❤️

**Comment by obfuscurity** [comment]
@deniszh thank you for all the fixes in #79. Nice to see this project updated for Python 3. 😃
